[package]
name = "tmt"
version = "0.1.0"
authors = ["rainy-me <github@rainy.me>"]
edition = "2018"
description = "rust terminal stopwatch timer"
license = "MIT"
repository = "https://github.com/rainy-me/tmt"
